### ISSUE TITLE
App crashes if WiFi is not enabled during scanning

### ISSUE THREAD

**Issue by dmitriy-ilchenko** [csicar/Ning#28]
The app crashes if you start scanning with WiFi disabled. Stack trace:
```
2020-09-19 02:16:19.514 4501-4501/de.csicar.ning E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.csicar.ning, PID: 4501
    kotlin.KotlinNullPointerException
        at de.csicar.ning.ScanRepository$startScan$2.invokeSuspend(ScanRepository.kt:43)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)
```

**Comment by dmitriy-ilchenko** [comment]
I think the problem is with these lines:
```
val networkData =
                InterfaceScanner.getNetworkInterfaces()
                    .also { Log.d(TAG, "NetworkInterfaces: $it") }
                    .find { it.interfaceName == interfaceName }!!
```
Maybe InterfaceScanner.getNetworkInterfaces() returned a list containing a null element. Or because of '!!' operator at the end.

**Comment by dmitriy-ilchenko** [comment]
I found out that if Wifi is disabled, but mobile network is enabled, it still shows 'wlan0' in the toolbar instead of 'rmnet0'. If they both disabled, it also shows 'wlan0'. I guess this is connected to this issue.

**Comment by dmitriy-ilchenko** [comment]
Also network interfaces are not updated when you turn Wifi on/off while app is running.

**Comment by csicar** [comment]
Yeah, that is an oversight in my part. Iguess the expected behaviour would be showing a screen explaining, that the interface needs to be enabled.

For the last issue: https://stackoverflow.com/questions/25678216/android-internet-connectivity-change-listener
